# Generated by Django 5.2.5 on 2025-08-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryCustody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Accessory Custody',
                'verbose_name_plural': 'Accessories Custody',
            },
        ),
        migrations.CreateModel(
            name='Custody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custody_date', models.DateField(verbose_name='Custody Date')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Return Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Custody',
                'verbose_name_plural': 'Custodies',
                'ordering': ['-custody_date'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Device Name (Arabic)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Device Name (English)')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Serial Number')),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('lost', 'Lost')], default='available', max_length=50, verbose_name='Status')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Accessory Name (Arabic)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Accessory Name (English)')),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('damaged', 'Damaged'), ('lost', 'Lost')], default='new', max_length=50, verbose_name='Condition')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Accessory',
                'verbose_name_plural': 'Accessories',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCustody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Device Custody',
                'verbose_name_plural': 'Device Custodies',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Device Type (Arabic)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Device Type (English)')),
            ],
            options={
                'verbose_name': 'Device Type',
                'verbose_name_plural': 'Device Types',
                'ordering': ['name_en'],
            },
        ),
    ]
