# Generated by Django 5.2.5 on 2025-08-26 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='custody',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='deviceaccessory',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='devices.device', verbose_name='Device'),
        ),
        migrations.AddField(
            model_name='accessorycustody',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.deviceaccessory'),
        ),
        migrations.AddField(
            model_name='devicecustody',
            name='accessories',
            field=models.ManyToManyField(related_name='custodies', through='devices.AccessoryCustody', to='devices.deviceaccessory', verbose_name='Accessories'),
        ),
        migrations.AddField(
            model_name='devicecustody',
            name='custody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_links', to='devices.custody'),
        ),
        migrations.AddField(
            model_name='devicecustody',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
        migrations.AddField(
            model_name='accessorycustody',
            name='device_custody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicecustody'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.devicetype', verbose_name='Device Type'),
        ),
    ]
