# Generated by Django 5.2.5 on 2025-09-05 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custody',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='deviceaccessory',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='devices.device', verbose_name='Device'),
        ),
        migrations.AddField(
            model_name='accessorycustody',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.deviceaccessory', verbose_name='Accessory'),
        ),
        migrations.AddField(
            model_name='devicecustody',
            name='accessories',
            field=models.ManyToManyField(related_name='custodies', through='devices.AccessoryCustody', to='devices.deviceaccessory', verbose_name='Accessories'),
        ),
        migrations.AddField(
            model_name='devicecustody',
            name='custody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.custody'),
        ),
        migrations.AddField(
            model_name='devicecustody',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custodies', to='devices.device'),
        ),
        migrations.AddField(
            model_name='accessorycustody',
            name='device_custody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicecustody'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.devicetype', verbose_name='Device Type'),
        ),
        migrations.AlterUniqueTogether(
            name='devicecustody',
            unique_together={('custody', 'device')},
        ),
    ]
