# Generated by Django 5.2.5 on 2025-08-27 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecustody',
            name='custody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.custody'),
        ),
    ]
