# Generated by Django 5.2.5 on 2025-09-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='it_service_tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IT Service Tag'),
        ),
    ]
