# Generated by Django 5.2.5 on 2025-08-26 21:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, unique=True, verbose_name='Ink Category (Arabic)')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='Ink Category (English)')),
            ],
            options={
                'verbose_name': 'Ink Category',
                'verbose_name_plural': 'Ink Categories',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='OfficeSupplyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, unique=True, verbose_name='Supply Category (Arabic)')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='Supply Category (English)')),
            ],
            options={
                'verbose_name': 'Supply Category',
                'verbose_name_plural': 'Supply Categories',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='InkInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Ink Name (Arabic)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Ink Name (English)')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inks', to='inventories.inkcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Ink',
                'verbose_name_plural': 'Inks',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficeSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Supply Name (Arabic)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Supply Name (English)')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='inventories.officesupplycategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Office Supply',
                'verbose_name_plural': 'Office Supplies',
                'ordering': ['name_en'],
            },
        ),
    ]
