# Generated by Django 5.2.5 on 2025-09-12 14:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField(verbose_name='Quantity Used')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason / Purpose')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Requested At')),
                ('ink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='inventories.inkinventory', verbose_name='Ink')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Ink Request',
                'verbose_name_plural': 'Ink Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
